# Methods other than papers...

Import the dataset from the device of the alloted research paper.

In [6]:
# this is from folder P, which contain postive datapoints. 

import pandas as pd
import os

folder_path = 'C:/Users/nitin_2n4diox/Downloads/P'
dataframes_list = []

for file_name in os.listdir(folder_path):
    file_path = os.path.join(folder_path, file_name)
    with open(file_path, 'r') as file:
        text = file.read()
        dataframes_list.append(pd.DataFrame([str(text)], columns=['Text'], dtype=str))

df1 = pd.concat(dataframes_list, ignore_index=True, axis=0)

In [35]:
df1['actual_label(Y)']='1'
df1['S']='1'
df1

                                                   Text actual_label(Y)  S
0     AC   P0A770; P77145;\nManganese transport prot...               1  1
1     AC   P0A769; P77145;\nManganese transport prot...               1  1
2     AC   P37329;\nMolybdate-binding periplasmic pr...               1  1
3     AC   P0AF02; P09834; P77537;\nMolybdenum trans...               1  1
4     AC   P0AF01; P09834; P77537;\nMolybdenum trans...               1  1
...                                                 ...             ... ..
2394  AC   P01501; P01503;\nMelittin precursor (Alle...               1  1
2395  AC   P40260;\nAmmonium transporter MEP1.\n"Clo...               1  1
2396  AC   P41948;\nAmmonium transporter MEP2.\n"A f...               1  1
2397  AC   P30344;\nMercury resistance probable Hg t...               1  1
2398  AC   Q10419;\nMesentericin Y105 secretion prot...               1  1

[2399 rows x 3 columns]

In [8]:
# this is from folder Q, which contain postive datapoints but these will be used for unlabeled datapoints.

import pandas as pd
import os

folder_path = 'C:/Users/nitin_2n4diox/Downloads/Q'
dataframes_list = []

for file_name in os.listdir(folder_path):
    file_path = os.path.join(folder_path, file_name)
    with open(file_path, 'r') as file:
        text = file.read()
        dataframes_list.append(pd.DataFrame([str(text)], columns=['Text'], dtype=str))

df2 = pd.concat(dataframes_list, ignore_index=True, axis=0)

In [36]:
df2['actual_label(Y)']='1'
df2['S']='0'
df2

                                                  Text actual_label(Y)  S
0    AC   P46492;\nProbable D-methionine transport ...               1  0
1    AC   Q97TN5;\nProbable manganese transport pro...               1  0
2    AC   P57788; Q9DEY5; Q9DG24;\nMonocarboxylate ...               1  0
3    AC   O61703;\nPhosphate carrier protein, mitoc...               1  0
4    AC   Q9C8H0;\nMultidrug resistance-associated ...               1  0
..                                                 ...             ... ..
343  AC   P13345;\nLysis protein for colicin E6 pre...               1  0
344  AC   P02911;\nLysine-arginine-ornithine-bindin...               1  0
345  AC   Q89A97;\nMultidrug resistance-like ATP-bi...               1  0
346  AC   O80725;\nMultidrug resistance protein 4 (...               1  0
347  AC   Q8FAX1;\nMultidrug resistance protein mdt...               1  0

[348 rows x 3 columns]

In [10]:
# this is from folder N, which contain negative datapoints but these will be used for unlabeled datapoints.

import pandas as pd
import os

folder_path = 'C:/Users/nitin_2n4diox/Downloads/N'
dataframes_list = []

for file_name in os.listdir(folder_path):
    file_path = os.path.join(folder_path, file_name)
    with open(file_path, 'r') as file:
        text = file.read()
        dataframes_list.append(pd.DataFrame([str(text)], columns=['Text'], dtype=str))

df3 = pd.concat(dataframes_list, ignore_index=True, axis=0)

In [37]:
df3['actual_label(Y)']='0'
df3['S']='0'
df3

                                                   Text actual_label(Y)  S
0     AC   Q20YV7;\nS-adenosylmethionine synthetase ...               0  0
1     AC   Q5FSK6;\nS-adenosylmethionine synthetase ...               0  0
2     AC   Q2RK28;\nS-adenosylmethionine synthetase ...               0  0
3     AC   P78003;\nS-adenosylmethionine synthetase ...               0  0
4     AC   Q9RL99; Q68VX2;\nS-adenosylmethionine syn...               0  0
...                                                 ...             ... ..
4553  AC   Q8CU52;\nAlkylmercury lyase (EC 4.99.1.2)...               0  0
4554  AC   Q5R6F1;\nMesoderm development candidate 2...               0  0
4555  AC   P44502;\nCystathionine gamma-synthase (EC...               0  0
4556  AC   P66875; O53427;\nCystathionine gamma-synt...               0  0
4557  AC   Q6A816;\nArgininosuccinate lyase (EC 4.3....               0  0

[4558 rows x 3 columns]

In [42]:
#CONCAT ALL DATA 
df= pd.concat([df1, df2, df3], axis=0,sort=False)

In [43]:
#to make text from pandas.core.Series.series
df.to_csv('file4.csv', index=False)

In [45]:
DF = pd.read_csv('file4.csv')
DF

                                                   Text  actual_label(Y)  S
0     AC   P0A770; P77145;\nManganese transport prot...                1  1
1     AC   P0A769; P77145;\nManganese transport prot...                1  1
2     AC   P37329;\nMolybdate-binding periplasmic pr...                1  1
3     AC   P0AF02; P09834; P77537;\nMolybdenum trans...                1  1
4     AC   P0AF01; P09834; P77537;\nMolybdenum trans...                1  1
...                                                 ...              ... ..
7300  AC   Q8CU52;\nAlkylmercury lyase (EC 4.99.1.2)...                0  0
7301  AC   Q5R6F1;\nMesoderm development candidate 2...                0  0
7302  AC   P44502;\nCystathionine gamma-synthase (EC...                0  0
7303  AC   P66875; O53427;\nCystathionine gamma-synt...                0  0
7304  AC   Q6A816;\nArgininosuccinate lyase (EC 4.3....                0  0

[7305 rows x 3 columns]

In [15]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [16]:
messages=DF.copy()
messages.head()

                                                Text  actual_label(Y)  S
0  AC   P0A770; P77145;\nManganese transport prot...                1  1
1  AC   P0A769; P77145;\nManganese transport prot...                1  1
2  AC   P37329;\nMolybdate-binding periplasmic pr...                1  1
3  AC   P0AF02; P09834; P77537;\nMolybdenum trans...                1  1
4  AC   P0AF01; P09834; P77537;\nMolybdenum trans...                1  1

In [17]:
type(messages['Text'][0])

str

# text preprocessing

In [18]:
##text preprocessing
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['Text'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [19]:
corpus[40]

'ac p c p small conduct mechanosensit channel genom sequenc shigella flexneri insight pathogen comparison genom escherichia coli k complet genom sequenc compar genom shigella flexneri serotyp strain function mechanosensit channel particip regul osmot pressur chang within cell form ion channel nanosiemen conduct slight prefer anion channel sensit voltag similar subunit homoheptam similar subcellular locat cell inner membran multi pass membran protein similar similar belong msc tc famili complet proteom inner membran ion transport ionic channel membran transmembran transport ththree'

In [20]:
## TFidf Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_v=TfidfVectorizer(max_features=5000,ngram_range=(1,3))
X=tfidf_v.fit_transform(corpus).toarray()

In [24]:
X.shape
type(X)

numpy.ndarray

In [47]:
s=DF['S']
s=pd.Series(s)
y_orig = DF['actual_label(Y)']
type(y_orig)

df = pd.concat([pd.DataFrame(X), y_orig, s], axis=1)
df

,0,1,2,3,4,5,6,7,8,9,...,4992,4993,4994,4995,4996,4997,4998,4999,actual_label(Y),S
0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
1,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
2,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
3,0.0,0.0,0.066113,0.079379,0.079379,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
4,0.0,0.0,0.050988,0.061219,0.061219,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7300,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
7301,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
7302,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
7303,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
7304,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0

# Standard Classifier Model

In [69]:
""" Random Forest Classifier Model """

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(
    n_estimators = 100,  # Use 100 trees
    n_jobs = -1 # Use all CPU cores
)

rf.fit(X, s)

""" Store the scores assigned by this approach """

results = pd.DataFrame({
    'truth'      : y_orig,   # The true labels
    'label'      : s,        # The labels that model sees
    'output_std' : rf.predict_proba(X)[:,1]   # Probability Scores
}, columns = ['truth', 'label', 'output_std'])

In [70]:
# by taking a threshold value of probability decide the positive and negative classs as 1 and 0 respectively

y_comp=[]
for i in range(len(results['truth'])):
    if results['output_std'][i] > 0.2:   ####....here i tried many probability values and took best one according to performance
        y_comp.append(1)
    else:
        y_comp.append(0)

        
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, roc_curve



# Calculate accuracy
accuracy = accuracy_score(results['truth'], y_comp)

# Calculate F1 score
f1 = f1_score(results['truth'], y_comp)

# Calculate AUC-ROC score
auc_roc = roc_auc_score(results['truth'], y_comp)

# Get ROC curve values
#fpr, tpr, thresholds = roc_curve(actual_label, f_pred)

print("Accuracy:", accuracy)
print("F1 score:", f1)
print("AUC-ROC score:", auc_roc)

Accuracy: 0.9631759069130732
F1 score: 0.9487911669522178
AUC-ROC score: 0.9520499685883343

# Bagging Model of PU

1.Create a training set by combining all positive data points with a random sample from the unlabeled points, with replacement.

2.Build a classifier from this "bootstrap" sample, treating positive and unlabeled data points as positives and negatives,         respectively.

3.Apply the classifier to whatever unlabeled data points were not included in the random sample – hereafter called OOB ("out of   bag") points – and record their scores.

4.Repeat the three steps above many times and finally assign to each point the average of the OOB scores it has received.

In [71]:
X = pd.DataFrame(X)

In [72]:
X['s']=s

In [73]:
X

,0,1,2,3,4,5,6,7,8,9,...,4991,4992,4993,4994,4995,4996,4997,4998,4999,s
0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,0.0,0.0,0.066113,0.079379,0.079379,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,0.0,0.0,0.050988,0.061219,0.061219,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7300,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
7301,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
7302,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
7303,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
7304,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [88]:
from sklearn.tree import DecisionTreeClassifier
estimator = DecisionTreeClassifier(random_state=42)

""" Indices of positive and unlabeled data points """
iP = s[s > 0].index
iU = s[s <= 0].index

""" For each data point, keep track of how many times it has been OOB """
num_oob = pd.DataFrame(np.zeros(shape = s.shape), index = s.index)
sum_oob = pd.DataFrame(np.zeros(shape = s.shape), index = s.index)

n_estimators = 1000
for _ in range(n_estimators):
    # Get a bootstrap sample of unlabeled points for this round
    ib = np.random.choice(iU, replace=True, size = len(iP))

    # Find the OOB data points for this round
    i_oob = list(set(iU) - set(ib))

    # Get the training data (ALL positives and the bootstrap sample of unlabeled points) and build the tree
    Xb = pd.concat([X[s > 0],X.loc[ib]])
    yb = pd.concat([s[s > 0], s.loc[ib]])
    estimator.fit(Xb, yb)
    
    # Record the OOB scores from this round
    sum_oob.loc[i_oob, 0] += estimator.predict_proba(X.loc[i_oob])[:,1]
    num_oob.loc[i_oob, 0] += 1

""" Finally, store the probabilities assigned by this approach """
results['output_bag'] = sum_oob / num_oob

In [89]:
## by taking a threshold value of probability decide the positive and negative classs as 1 and 0 respectively.

y2_comp=[]
for i in range(len(results['truth'])):
    if results['output_bag'][i] > 0.40:  ####....here i tried many probability values and took best one according to performance
        y2_comp.append(1)
    else:
        y2_comp.append(0)

# Calculate accuracy
accuracy = accuracy_score(results['truth'], y2_comp)

# Calculate F1 score
f1 = f1_score(results['truth'], y2_comp)

# Calculate AUC-ROC score
auc_roc = roc_auc_score(results['truth'], y2_comp)

# Get ROC curve values
#fpr, tpr, thresholds = roc_curve(actual_label, f_pred)

print("Accuracy:", accuracy)
print("F1 score:", f1)
print("AUC-ROC score:", auc_roc)

Accuracy: 0.6239561943874059
F1 score: 0.0
AUC-ROC score: 0.5

# Two-Step Strategy Model

1.Identify a subset of the unlabeled data points that can be confidently labeled as negatives. ("reliable negatives.")

2.Use the positive and negative data points to train a standard classifier and apply it to the remaining unlabeled points.

In [86]:
# Create a new target vector, with 1 for positive, -1 for unlabeled, and 0 for "reliable negative" (there are no reliable negatives to start with)
ys = 2 * y - 1

# Get the scores from before
pred = rf.predict_proba(X)[:,1]

# Find the range of scores given to positive data points
range_P = [min(pred * (ys > 0)), max(pred * (ys > 0))]

# STEP 1
# If any unlabeled point has a score above all known positives, or below all known positives, label it accordingly
iP_new = ys[(ys < 0) & (pred >= range_P[1])].index
iN_new = ys[(ys < 0) & (pred <= range_P[0])].index
ys.loc[iP_new] = 1
ys.loc[iN_new] = 0

   

# Classifier to be used for step 2
rf2 = RandomForestClassifier(n_estimators = 100, n_jobs = -1)

# Limit to 10 iterations (this is arbitrary, but otherwise this approach can take a very long time)
for i in range(10):
    # If step 1 didn't find new labels, we're done
    if len(iP_new) + len(iN_new) == 0 and i > 0:
        break
    
    print(
        'Step 1 labeled %d new positives and %d new negatives.' 
        % (len(iP_new), len(iN_new))
    )
    print('Doing step 2... ', end = '')
    
    # STEP 2
    # Retrain on new labels and get new scores
    rf2.fit(X, ys)
    pred = rf2.predict_proba(X)[:,-1]
    
    # Find the range of scores given to positive data points
    range_P = [min(pred * (ys > 0)), max(pred * (ys > 0))]
    
    # Repeat step 1
    iP_new = ys[(ys < 0) & (pred >= range_P[1])].index
    iN_new = ys[(ys < 0) & (pred <= range_P[0])].index
    ys.loc[iP_new] = 1
    ys.loc[iN_new] = 0
    
    
# Lastly, get the Probabilities assigned by this approach    
results['output_stp'] = pred

Step 1 labeled 0 new positives and 2482 new negatives.
Doing step 2... Step 1 labeled 0 new positives and 434 new negatives.
Doing step 2... Step 1 labeled 0 new positives and 223 new negatives.
Doing step 2... Step 1 labeled 0 new positives and 133 new negatives.
Doing step 2... Step 1 labeled 0 new positives and 94 new negatives.
Doing step 2... Step 1 labeled 0 new positives and 57 new negatives.
Doing step 2... Step 1 labeled 0 new positives and 52 new negatives.
Doing step 2... Step 1 labeled 0 new positives and 39 new negatives.
Doing step 2... Step 1 labeled 0 new positives and 39 new negatives.
Doing step 2... Step 1 labeled 0 new positives and 25 new negatives.
Doing step 2...

In [87]:
## by taking a threshold value of probability decide the positive and negative classs as 1 and 0 respectively.


y3_comp=[]
for i in range(len(results['truth'])):
    if results['output_stp'][i] > 0.03:  ####....here i tried many probability values and took best one according to performance
        y3_comp.append(1)
    else:
        y3_comp.append(0)

# Calculate accuracy
accuracy = accuracy_score(results['truth'], y3_comp)

# Calculate F1 score
f1 = f1_score(results['truth'], y3_comp)

# Calculate AUC-ROC score
auc_roc = roc_auc_score(results['truth'], y3_comp)

# Get ROC curve values
#fpr, tpr, thresholds = roc_curve(actual_label, f_pred)

print("Accuracy:", accuracy)
print("F1 score:", f1)
print("AUC-ROC score:", auc_roc)

Accuracy: 0.8848733744010951
F1 score: 0.8660614747571269
AUC-ROC score: 0.9057196785579482

# Average of 3 Approaches

taking average of probabilistic score of all three approach.

In [90]:
# For each data point, calculate the average score from the three approaches
results['output_all'] = results[[
    'output_std', 'output_bag', 'output_stp'
]].mean(axis = 1)

In [91]:
y4_comp=[]
for i in range(len(results['truth'])):
    if results['output_all'][i] > 0.1:
        y4_comp.append(1)
    else:
        y4_comp.append(0)

# Calculate accuracy
accuracy = accuracy_score(results['truth'], y4_comp)

# Calculate F1 score
f1 = f1_score(results['truth'], y4_comp)

# Calculate AUC-ROC score
auc_roc = roc_auc_score(results['truth'], y4_comp)

# Get ROC curve values
#fpr, tpr, thresholds = roc_curve(actual_label, f_pred)

print("Accuracy:", accuracy)
print("F1 score:", f1)
print("AUC-ROC score:", auc_roc)

Accuracy: 0.9709787816563997
F1 score: 0.9604772557792691
AUC-ROC score: 0.9643775498517431